#pragma once
#include <string>
#include <memory>
#include <grpcpp/grpcpp.h>
#include "video_service.grpc.pb.h" // Automatically generated by CMake!

namespace BitFlow {

class GrpcReporter {
public:
    GrpcReporter(const std::string& targetAddress);
    ~GrpcReporter();

    // Sends a real-time tracking frame back to the Node.js API Gateway
    bool reportProgress(const std::string& jobId, int percentage, const std::string& status, const std::string& errorMessage = "");

private:
    std::unique_ptr<bitflow::BitFlowCallbackService::Stub> stub_;
};

} // namespace BitFlow